{
 "title": "NVIDIA DCGM  그래픽 카드 Info",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
    }
   },
   { "name": "gpu", "query": { "query": "label_values(gpu)" } },
   {
    "name": "cpu_instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "cpu_job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "CPU 정보", "type": "text", "gridPos": { "h": 1, "w": 5, "x": 0, "y": 1 } },
  { "title": "GPU 0 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 6, "y": 1 } },
  { "title": "GPU 1 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 10, "y": 1 } },
  { "title": "GPU 2 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 14, "y": 1 } },
  { "title": "GPU 3 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 18, "y": 1 } },
  {
   "title": "CPU 사용량",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$cpu_instance\",job=\"$cpu_job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$cpu_instance\",job=\"$cpu_job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$cpu_instance\",job=\"$cpu_job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"0\"})"
    }
   ]
  },
  {
   "title": "GPU 전력",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"0\"})"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"1\"})"
    }
   ]
  },
  {
   "title": "GPU 전력",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"1\"})"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"2\"})"
    }
   ]
  },
  {
   "title": "GPU 전력",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"2\"})"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"3\"})"
    }
   ]
  },
  {
   "title": "GPU 전력",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"3\"})"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$cpu_instance\",job=\"$cpu_job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$cpu_instance\",job=\"$cpu_job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$cpu_instance\",job=\"$cpu_job\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$cpu_instance\",job=\"$cpu_job\"}"
    }
   ]
  },
  { "title": "GPU 4 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 6, "y": 6 } },
  { "title": "GPU 5 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 10, "y": 6 } },
  { "title": "GPU 6 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 14, "y": 6 } },
  { "title": "GPU 7 번", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 18, "y": 6 } },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"4\"})"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"4\"})"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"5\"})"
    }
   ]
  },
  {
   "title": "GPU 전력",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"5\"})"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"6\"})"
    }
   ]
  },
  {
   "title": "GPU 전력",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"6\"})"
    }
   ]
  },
  {
   "title": "GPU 온도",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"7\"})"
    }
   ]
  },
  {
   "title": "GPU 전력",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"7\"})"
    }
   ]
  },
  {
   "title": "GPU 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 온도량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 전력량",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"${instance}\", gpu=~\"${gpu}\"} * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}