{
 "title": "Server Info",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Svserver2 | 미버스 서빙", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "CPU 정보", "type": "text", "gridPos": { "h": 1, "w": 5, "x": 0, "y": 1 } },
  { "title": "GPU 정보", "type": "text", "gridPos": { "h": 1, "w": 19, "x": 5, "y": 1 } },
  {
   "title": "CPU 사용량",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "GPU 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"dcgm_exporter:9400\", gpu=~\"0|1|2|3|4|5|6|7\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 전력량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"dcgm_exporter:9400\", gpu=~\"0|1|2|3|4|5|6|7\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} - node_memory_MemFree_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} - (node_memory_Cached_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} + node_memory_Buffers_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} + node_memory_SReclaimable_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} * 100) / node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "RAM 전체량",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"}"
    }
   ]
  },
  { "title": "Trserver4 | 스포키 데브", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "CPU 정보", "type": "text", "gridPos": { "h": 1, "w": 5, "x": 0, "y": 9 } },
  { "title": "GPU 정보", "type": "text", "gridPos": { "h": 1, "w": 19, "x": 5, "y": 9 } },
  {
   "title": "CPU 사용량",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "GPU 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"dcgm_exporter:9400\", gpu=~\"0|1|2|3|4|5|6|7\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 전력량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"dcgm_exporter:9400\", gpu=~\"0|1|2|3|4|5|6|7\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} - node_memory_MemFree_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} - (node_memory_Cached_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} + node_memory_Buffers_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} + node_memory_SReclaimable_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} * 100) / node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "RAM 전체량",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"}"
    }
   ]
  },
  { "title": "SERVER3 | 베리미 데브", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "title": "CPU 정보", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 0, "y": 17 } },
  { "title": "GPU 정보", "type": "text", "gridPos": { "h": 1, "w": 19, "x": 5, "y": 17 } },
  {
   "title": "CPU 사용량",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "GPU 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"dcgm_exporter:9400\", gpu=~\"0|1|2|3|4|5|6|7\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 전력량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"dcgm_exporter:9400\", gpu=~\"0|1|2|3|4|5|6|7\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} - node_memory_MemFree_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} - (node_memory_Cached_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} + node_memory_Buffers_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} + node_memory_SReclaimable_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "RAM 사용량",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"} * 100) / node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "RAM 전체량",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\",job=\"node_exporter\"}"
    }
   ]
  }
 ]
}